POST http://localhost:4000/doctor/BasicRegister HTTP/1.1
Content-Type: application/json

{
    "firstName" :"Swami",
    "lastName" :"Vivekananda",
    "countryCode": "+91",
    "phoneNumber" :"9999999999",
    "userPassword": "1234",
    "hospitalName" :"Apollo Hospitals",
    "state" :"west bengal",
    "userPincode" :"711221"
}

### login doctor
POST http://localhost:4000/doctor/login HTTP/1.1
Content-Type: application/json

{
    "phoneNumber" :"7980143133",
    "userPassword": "1234"
}

### doctor finding patient
POST http://localhost:4000/doctor/findPatients HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo1MywiaWF0IjoxNjE5Njc0MDkwLCJleHAiOjE2MTk3NjA0OTB9.V1ZiXnpyI3PXekBzcB_YCjQuOTv819liLdcnwELCZo0
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo1MywiaWF0IjoxNjE5Njc0MDkwLCJleHAiOjE2MjAyNzg4OTB9.6KWeUeE1eWGy6tXkjvcSk3eiffDZB1ATVURy6XHByhw

### finding all patients belongs to a specific hospital
POST http://localhost:4000/doctor/patientsOfHospital HTTP/1.1
Content-Type: application/json

{
    "hospitalName":"Apollo Hospitals"
}


### Patient register
POST http://localhost:4000/patient/BasicRegister HTTP/1.1
Content-Type: application/json

{
    "patientName" :"Avik Sarkar",
    "countryCode": "+91",
    "patientPhoneNumber" :"9999999999",
    "patientAddress": "Nischinda Ghoshpara",
    "patientEmail":"aviksarkar@gmail.com",
    "patientPassword": "1234",
    "userID": 53
}

### patient login
POST http://localhost:4000/patient/Login HTTP/1.1
Content-Type: application/json

{
    "patientPhoneNumber" :"7980143133",
    "patientPassword": "1234"
}

### update profile
PUT http://localhost:4000/patient/updateProfile HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoyLCJpYXQiOjE2MTk2MDQ0MjUsImV4cCI6MTYxOTY5MDgyNX0.QT7VVB9jw6FoGx2c9Ztz41TGaAham7epPkwh6ZFIo7w
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE2MTkxOTIwNDEsImV4cCI6MTYxOTI3ODQ0MX0.uSMtxRNqq0ep0lmKIMlrMzUpcN8r-LdKO__TYRORC0A

{
    "patientName" :"Alok Laha",
    "patientPhoneNumber" :"7980143133",
    "patientAddress": "Nischinda bally",
    "patientEmail":"aloklaha98@gmail.com",
    "patientPassword": "1234",
    "userID": 1
}


