POST http://localhost:4000/doctor/BasicRegister HTTP/1.1
Content-Type: application/json

{
    "firstName" :"ddefge",
    "lastName" :"drhfg",
    "phoneNumber" :"8931224750",
    "userPassword": "1234",
    "hospitalName" :"Apollo Hospitals",
    "state" :"west bengal",
    "userPincode" :"711221"
}

### login doctor
POST http://localhost:4000/doctor/login HTTP/1.1
Content-Type: application/json

{
    "phoneNumber" :"7980143133",
    "userPassword": "1234"
}

### doctor finding patient
POST http://localhost:4000/doctor/findPatients HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE2MTkxOTIwNDEsImV4cCI6MTYxOTI3ODQ0MX0.uSMtxRNqq0ep0lmKIMlrMzUpcN8r-LdKO__TYRORC0A

### finding all patients belongs to a specific hospital
POST http://localhost:4000/doctor/patientsOfHospital HTTP/1.1
Content-Type: application/json

{
    "hospitalName":"Apollo Hospitals"
}


### Patient register
POST http://localhost:4000/patient/BasicRegister HTTP/1.1
Content-Type: application/json

{
    "patientName" :"Avik",
    "patientPhoneNumber" :"7970143133",
    "patientAddress": "Nischinda Ghoshpara",
    "patientEmail":"avik@gmail.com",
    "patientPassword": "1234",
    "userID": 1
}

### patient login
POST http://localhost:4000/patient/Login HTTP/1.1
Content-Type: application/json

{
    "patientPhoneNumber" :"9051224756",
    "patientPassword": "1234"
}

### update profile
POST http://localhost:4000/patient/updateProfile HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE2MTkxOTAyODYsImV4cCI6MTYxOTI3NjY4Nn0.zHMAEeia0_6q1TrV2mqJ7mQb8pu_nMujbN7MNKIZQfY

{
    "patientName" :"Ayan",
    "patientPhoneNumber" :"9051224756",
    "patientAddress": "Nischinda bally",
    "patientEmail":"ayan@gmail.com",
    "patientPassword": "1234",
    "userID": 1
}


