name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
    
      - run: npm i
     
      - run: npm run build --if-present
      - name: Mysql test
      - run: sudo service mysql start
      - run: mysql -uroot -proot -e "SHOW DATABASES"
      - run: mysql -uroot -proot -e "CREATE DATABASE test_db"
      - run: mysql -uroot -proot -e "SHOW DATABASES"
